## Preliminaries

### Import statements

In [1]:
import os
import csv
import re
import git
import bisect
import platform, psutil, torch
from time import time
from collections import Counter
from copy import deepcopy
import requests
from lxml import etree
import pandas as pd
import spacy
from MyCapytain.resolvers.cts.local import CtsCapitainsLocalResolver
from MyCapytain.resources.prototypes.metadata import UnknownCollection
from dicesapi import DicesAPI

### Global values

In [2]:
# local data directory, used for both input and output
data_dir = "data"

# corpus repositories
repositories = [
    {
        "label": "Perseus Greek",
        "base_url": "https://github.com/perseusDL",
        "repo_name": "canonical-greekLit",
        "commit": "beed7ea8926266ad90935c183f2bcf2caf4ac0dc",
    },
]
# XML namespaces used by Perseus TEI, needed for xpath
nsmap = {
    "cts": "http://chs.harvard.edu/xmlns/cts",
    "tei": "http://www.tei-c.org/ns/1.0",
    "py": "http://codespeak.net/lxml/objectify/pytype",
}

# https://huggingface.co/chcaa/grc_odycy_joint_trf/blob/main/grc_odycy_joint_trf-0.7.0-py3-none-any.whl
spacy_model = "grc_odycy_joint_trf"

## Get texts

### Create local clone of Perseus repository

In [3]:
print('Checking for local text repositories...')
for rec in repositories:
    dest_path = os.path.join(data_dir, rec["repo_name"])
    remote_url = rec["base_url"] + "/" + rec["repo_name"] + ".git"

    if os.path.exists(dest_path):
        print(f' - {dest_path} exists!')
        repo = git.Repo(dest_path)
    else:
        print(f' - retrieving {dest_path}')
        repo = git.Repo.clone_from(remote_url, dest_path)

    # reset to specified commit
    print(f" - resetting to commit {rec['commit']}")
    repo.head.reset(rec["commit"], working_tree=True)

Checking for local text repositories...
 - data/canonical-greekLit exists!
 - resetting to commit beed7ea8926266ad90935c183f2bcf2caf4ac0dc

### Read text metadata

In [4]:
corpus_file = os.path.join(data_dir, "corpus.tsv")
print(f"Reading text metadata from {corpus_file}")

corpus = []

with open(corpus_file) as f:
    reader = csv.DictReader(f, delimiter="\t")
    for rec in reader:
        corpus.append(dict(
            author = rec["author"],
            title = rec["title"],
            urn = rec["urn"],
            prefix = rec["prefix"],
        ))
print(f" - got data on {len(corpus)} texts")

Reading text metadata from data/corpus.tsv
 - got data on 115 texts

### Load XML using CTS API

#### initialize local resolver

In [5]:
repo_paths = [os.path.join(data_dir, rec["repo_name"]) for rec in repositories]
resolver = CtsCapitainsLocalResolver(repo_paths)

#### retrieve the texts

In [6]:
print("Retrieving texts...")
for text in corpus:
    try:
        text["xml"] = resolver.getTextualNode(text["urn"], text["prefix"]).xml
    except UnknownCollection:
        print(f" - {text['author']} {text['title']} {text['prefix']} failed")

print(len([text for text in corpus if text.get("xml") is not None]), "texts retrieved")

Retrieving texts...
115 texts retrieved

### Extract verse lines

#### build an array of lines

In [7]:
print("Building line arrays...")
nlines = 0

for i, text in enumerate(corpus):
    print(f"[{i+1}/{len(corpus)}]", text["author"], text["title"], text["prefix"], end="\t")

    # bail if no XML
    if text.get("xml") is None:
        print("failed: no XML")
        continue

    # initialize line array
    text['line_array'] = []

    # work from copy of xml
    xml = deepcopy(text["xml"])
        
    # remove notes
    for note in xml.findall(".//tei:note", namespaces=nsmap):
        note.clear(keep_tail=True)
        
    # remove deleted lines
    for del_ in xml.findall(".//tei:del", namespaces=nsmap):
        del_.clear(keep_tail=True)
        
    # iterate over verse lines
    for l in xml.findall(".//tei:l", namespaces=nsmap):
        line_num = l.get("n")
        if line_num is None:
            continue
        
        line_text = "".join(s for s in l.itertext())
        line_text = re.sub(r"\s+", " ", line_text).strip()
        text['line_array'].append(dict(
            n = line_num,
            seq = len(text['line_array']),
            text = line_text,
        ))

    print(len(text["line_array"]), "lines")
    nlines += len(text["line_array"])
print(f"Total: {nlines} lines")

Building line arrays...
[1/115] Homer Iliad 1	611 lines
[2/115] Homer Iliad 2	877 lines
[3/115] Homer Iliad 3	461 lines
[4/115] Homer Iliad 4	544 lines
[5/115] Homer Iliad 5	909 lines
[6/115] Homer Iliad 6	529 lines
[7/115] Homer Iliad 7	482 lines
[8/115] Homer Iliad 8	565 lines
[9/115] Homer Iliad 9	709 lines
[10/115] Homer Iliad 10	579 lines
[11/115] Homer Iliad 11	847 lines
[12/115] Homer Iliad 12	471 lines
[13/115] Homer Iliad 13	837 lines
[14/115] Homer Iliad 14	521 lines
[15/115] Homer Iliad 15	746 lines
[16/115] Homer Iliad 16	867 lines
[17/115] Homer Iliad 17	761 lines
[18/115] Homer Iliad 18	617 lines
[19/115] Homer Iliad 19	424 lines
[20/115] Homer Iliad 20	503 lines
[21/115] Homer Iliad 21	611 lines
[22/115] Homer Iliad 22	515 lines
[23/115] Homer Iliad 23	897 lines
[24/115] Homer Iliad 24	804 lines
[25/115] Homer Odyssey 1	444 lines
[26/115] Homer Odyssey 2	434 lines
[27/115] Homer Odyssey 3	497 lines
[28/115] Homer Odyssey 4	847 lines
[29/115] Homer Odyssey 5	493 lines
[30/115] Homer Odyssey 6	331 lines
[31/115] Homer Odyssey 7	347 lines
[32/115] Homer Odyssey 8	586 lines
[33/115] Homer Odyssey 9	566 lines
[34/115] Homer Odyssey 10	573 lines
[35/115] Homer Odyssey 11	640 lines
[36/115] Homer Odyssey 12	453 lines
[37/115] Homer Odyssey 13	440 lines
[38/115] Homer Odyssey 14	533 lines
[39/115] Homer Odyssey 15	557 lines
[40/115] Homer Odyssey 16	480 lines
[41/115] Homer Odyssey 17	606 lines
[42/115] Homer Odyssey 18	428 lines
[43/115] Homer Odyssey 19	604 lines
[44/115] Homer Odyssey 20	394 lines
[45/115] Homer Odyssey 21	434 lines
[46/115] Homer Odyssey 22	501 lines
[47/115] Homer Odyssey 23	371 lines
[48/115] Homer Odyssey 24	548 lines
[49/115] Apollonius Argonautica 1	1362 lines
[50/115] Apollonius Argonautica 2	1287 lines
[51/115] Apollonius Argonautica 3	1406 lines
[52/115] Apollonius Argonautica 4	1779 lines
[53/115] Quintus Posthomerica 1	834 lines
[54/115] Quintus Posthomerica 2	668 lines
[55/115] Quintus Posthomerica 3	788 lines
[56/115] Quintus Posthomerica 4	596 lines
[57/115] Quintus Posthomerica 5	666 lines
[58/115] Quintus Posthomerica 6	655 lines
[59/115] Quintus Posthomerica 7	739 lines
[60/115] Quintus Posthomerica 8	506 lines
[61/115] Quintus Posthomerica 9	551 lines
[62/115] Quintus Posthomerica 10	495 lines
[63/115] Quintus Posthomerica 11	502 lines
[64/115] Quintus Posthomerica 12	589 lines
[65/115] Quintus Posthomerica 13	573 lines
[66/115] Quintus Posthomerica 14	662 lines
[67/115] Triphiodorus Sack of Troy 	691 lines
[68/115] Nonnus Dionysiaca 1	535 lines
[69/115] Nonnus Dionysiaca 2	713 lines
[70/115] Nonnus Dionysiaca 3	445 lines
[71/115] Nonnus Dionysiaca 4	464 lines
[72/115] Nonnus Dionysiaca 5	622 lines
[73/115] Nonnus Dionysiaca 6	389 lines
[74/115] Nonnus Dionysiaca 7	369 lines
[75/115] Nonnus Dionysiaca 8	419 lines
[76/115] Nonnus Dionysiaca 9	322 lines
[77/115] Nonnus Dionysiaca 10	431 lines
[78/115] Nonnus Dionysiaca 11	522 lines
[79/115] Nonnus Dionysiaca 12	398 lines
[80/115] Nonnus Dionysiaca 13	569 lines
[81/115] Nonnus Dionysiaca 14	438 lines
[82/115] Nonnus Dionysiaca 15	423 lines
[83/115] Nonnus Dionysiaca 16	406 lines
[84/115] Nonnus Dionysiaca 17	397 lines
[85/115] Nonnus Dionysiaca 18	369 lines
[86/115] Nonnus Dionysiaca 19	349 lines
[87/115] Nonnus Dionysiaca 20	405 lines
[88/115] Nonnus Dionysiaca 21	346 lines
[89/115] Nonnus Dionysiaca 22	402 lines
[90/115] Nonnus Dionysiaca 23	321 lines
[91/115] Nonnus Dionysiaca 24	349 lines
[92/115] Nonnus Dionysiaca 25	573 lines
[93/115] Nonnus Dionysiaca 26	379 lines
[94/115] Nonnus Dionysiaca 27	342 lines
[95/115] Nonnus Dionysiaca 28	331 lines
[96/115] Nonnus Dionysiaca 29	382 lines
[97/115] Nonnus Dionysiaca 30	327 lines
[98/115] Nonnus Dionysiaca 31	283 lines
[99/115] Nonnus Dionysiaca 32	300 lines
[100/115] Nonnus Dionysiaca 33	388 lines
[101/115] Nonnus Dionysiaca 34	359 lines
[102/115] Nonnus Dionysiaca 35	392 lines
[103/115] Nonnus Dionysiaca 36	481 lines
[104/115] Nonnus Dionysiaca 37	778 lines
[105/115] Nonnus Dionysiaca 38	435 lines
[106/115] Nonnus Dionysiaca 39	407 lines
[107/115] Nonnus Dionysiaca 40	580 lines
[108/115] Nonnus Dionysiaca 41	428 lines
[109/115] Nonnus Dionysiaca 42	542 lines
[110/115] Nonnus Dionysiaca 43	450 lines
[111/115] Nonnus Dionysiaca 44	319 lines
[112/115] Nonnus Dionysiaca 45	359 lines
[113/115] Nonnus Dionysiaca 46	370 lines
[114/115] Nonnus Dionysiaca 47	742 lines
[115/115] Nonnus Dionysiaca 48	978 lines
Total: 64471 lines

#### index lines by starting character position

In [8]:
print("Building line indices...")
success = 0

for text in corpus:
    # start index at zero
    text["line_index"] = []
    cumsum = 0

    # iterate over line array, add length (plus 1 for spaces between lines)
    for line in text["line_array"]:
        text["line_index"].append(cumsum)
        cumsum += len(line["text"]) + 1

    # make sure the count works out
    if cumsum != len(" ".join(line["text"] for line in text["line_array"])) + 1:
        print(" - character count doesn't match:", text["author"], text["title"], text["prefix"])
    else:
        success += 1

print(success, " indices built successfully")

Building line indices...
115  indices built successfully

## Parse text with spaCy
### load spacy model

In [9]:
nlp = spacy.load(spacy_model)

### parse each text as one long string

Times below reflect the testing system:
- MacBook Pro M3
- 12 cores
- 18 GB RAM
- MPS acceleration

In [10]:
print(f"Parsing with {spacy_model}...")
_t0 = time()

for i, text in enumerate(corpus):
    print(f"[{i+1}/{len(corpus)}]", text["author"], text["title"], text["prefix"], end="\t")
    t0 = time()

    one_long_string = " ".join(line["text"] for line in text["line_array"])
    text["spacy_doc"] = nlp(one_long_string)

    t1 = time()
    print(len(text["spacy_doc"]), "tokens,", int(t1-t0), "seconds")

# format total run time
total_time = time()-_t0
h = int(total_time / 3600)
m = int((total_time - h*3600) / 60)
s = int(total_time - h*3600 - m*60)
print(f"total time: {h}:{m:02d}:{s:02d}")

Parsing with grc_odycy_joint_trf...
[1/115] Homer Iliad 1

/Users/chris/Documents/git/uva-common/venv/lib/python3.10/site-packages/thinc/shims/pytorch.py:114: FutureWarning: `torch.cuda.amp.autocast(args...)` is deprecated. Please use `torch.amp.autocast('cuda', args...)` instead.
  with torch.cuda.amp.autocast(self._mixed_precision):

5140 tokens, 9 seconds
[2/115] Homer Iliad 2	6822 tokens, 12 seconds
[3/115] Homer Iliad 3	3686 tokens, 6 seconds
[4/115] Homer Iliad 4	4341 tokens, 8 seconds
[5/115] Homer Iliad 5	7306 tokens, 13 seconds
[6/115] Homer Iliad 6	4247 tokens, 7 seconds
[7/115] Homer Iliad 7	3867 tokens, 7 seconds
[8/115] Homer Iliad 8	4560 tokens, 9 seconds
[9/115] Homer Iliad 9	5778 tokens, 10 seconds
[10/115] Homer Iliad 10	4751 tokens, 8 seconds
[11/115] Homer Iliad 11	6860 tokens, 12 seconds
[12/115] Homer Iliad 12	3741 tokens, 6 seconds
[13/115] Homer Iliad 13	6684 tokens, 12 seconds
[14/115] Homer Iliad 14	4241 tokens, 7 seconds
[15/115] Homer Iliad 15	6063 tokens, 11 seconds
[16/115] Homer Iliad 16	6970 tokens, 13 seconds
[17/115] Homer Iliad 17	6134 tokens, 11 seconds
[18/115] Homer Iliad 18	5030 tokens, 9 seconds
[19/115] Homer Iliad 19	3460 tokens, 6 seconds
[20/115] Homer Iliad 20	4080 tokens, 7 seconds
[21/115] Homer Iliad 21	5074 tokens, 9 seconds
[22/115] Homer Iliad 22	4326 tokens, 7 seconds
[23/115] Homer Iliad 23	7318 tokens, 13 seconds
[24/115] Homer Iliad 24	6838 tokens, 12 seconds
[25/115] Homer Odyssey 1	3733 tokens, 6 seconds
[26/115] Homer Odyssey 2	3727 tokens, 6 seconds
[27/115] Homer Odyssey 3	4213 tokens, 7 seconds
[28/115] Homer Odyssey 4	7157 tokens, 13 seconds
[29/115] Homer Odyssey 5	4224 tokens, 7 seconds
[30/115] Homer Odyssey 6	2850 tokens, 5 seconds
[31/115] Homer Odyssey 7	2867 tokens, 5 seconds
[32/115] Homer Odyssey 8	4928 tokens, 9 seconds
[33/115] Homer Odyssey 9	4720 tokens, 8 seconds
[34/115] Homer Odyssey 10	4849 tokens, 8 seconds
[35/115] Homer Odyssey 11	5302 tokens, 10 seconds
[36/115] Homer Odyssey 12	3778 tokens, 7 seconds
[37/115] Homer Odyssey 13	3722 tokens, 6 seconds
[38/115] Homer Odyssey 14	4539 tokens, 8 seconds
[39/115] Homer Odyssey 15	4716 tokens, 8 seconds
[40/115] Homer Odyssey 16	4078 tokens, 7 seconds
[41/115] Homer Odyssey 17	5190 tokens, 9 seconds
[42/115] Homer Odyssey 18	3662 tokens, 6 seconds
[43/115] Homer Odyssey 19	5123 tokens, 9 seconds
[44/115] Homer Odyssey 20	3323 tokens, 6 seconds
[45/115] Homer Odyssey 21	3663 tokens, 6 seconds
[46/115] Homer Odyssey 22	4183 tokens, 7 seconds
[47/115] Homer Odyssey 23	3150 tokens, 5 seconds
[48/115] Homer Odyssey 24	4594 tokens, 8 seconds
[49/115] Apollonius Argonautica 1	10407 tokens, 20 seconds
[50/115] Apollonius Argonautica 2	9897 tokens, 18 seconds
[51/115] Apollonius Argonautica 3	11255 tokens, 21 seconds
[52/115] Apollonius Argonautica 4	13748 tokens, 26 seconds
[53/115] Quintus Posthomerica 1	6343 tokens, 12 seconds
[54/115] Quintus Posthomerica 2	5187 tokens, 10 seconds
[55/115] Quintus Posthomerica 3	6068 tokens, 11 seconds
[56/115] Quintus Posthomerica 4	4559 tokens, 8 seconds
[57/115] Quintus Posthomerica 5	5212 tokens, 9 seconds
[58/115] Quintus Posthomerica 6	5127 tokens, 9 seconds
[59/115] Quintus Posthomerica 7	5735 tokens, 11 seconds
[60/115] Quintus Posthomerica 8	3845 tokens, 7 seconds
[61/115] Quintus Posthomerica 9	4337 tokens, 8 seconds
[62/115] Quintus Posthomerica 10	3918 tokens, 7 seconds
[63/115] Quintus Posthomerica 11	3863 tokens, 7 seconds
[64/115] Quintus Posthomerica 12	4625 tokens, 8 seconds
[65/115] Quintus Posthomerica 13	4399 tokens, 8 seconds
[66/115] Quintus Posthomerica 14	5093 tokens, 9 seconds
[67/115] Triphiodorus Sack of Troy 	4807 tokens, 9 seconds
[68/115] Nonnus Dionysiaca 1	3736 tokens, 7 seconds
[69/115] Nonnus Dionysiaca 2	4848 tokens, 9 seconds
[70/115] Nonnus Dionysiaca 3	2999 tokens, 5 seconds
[71/115] Nonnus Dionysiaca 4	3278 tokens, 6 seconds
[72/115] Nonnus Dionysiaca 5	4284 tokens, 8 seconds
[73/115] Nonnus Dionysiaca 6	2587 tokens, 5 seconds
[74/115] Nonnus Dionysiaca 7	2555 tokens, 4 seconds
[75/115] Nonnus Dionysiaca 8	3046 tokens, 5 seconds
[76/115] Nonnus Dionysiaca 9	2130 tokens, 4 seconds
[77/115] Nonnus Dionysiaca 10	3037 tokens, 5 seconds
[78/115] Nonnus Dionysiaca 11	3811 tokens, 7 seconds
[79/115] Nonnus Dionysiaca 12	2763 tokens, 5 seconds
[80/115] Nonnus Dionysiaca 13	3868 tokens, 7 seconds
[81/115] Nonnus Dionysiaca 14	2927 tokens, 5 seconds
[82/115] Nonnus Dionysiaca 15	2991 tokens, 5 seconds
[83/115] Nonnus Dionysiaca 16	2943 tokens, 5 seconds
[84/115] Nonnus Dionysiaca 17	2713 tokens, 5 seconds
[85/115] Nonnus Dionysiaca 18	2519 tokens, 4 seconds
[86/115] Nonnus Dionysiaca 19	2526 tokens, 4 seconds
[87/115] Nonnus Dionysiaca 20	2817 tokens, 5 seconds
[88/115] Nonnus Dionysiaca 21	2370 tokens, 4 seconds
[89/115] Nonnus Dionysiaca 22	2760 tokens, 5 seconds
[90/115] Nonnus Dionysiaca 23	2223 tokens, 4 seconds
[91/115] Nonnus Dionysiaca 24	2432 tokens, 4 seconds
[92/115] Nonnus Dionysiaca 25	3965 tokens, 7 seconds
[93/115] Nonnus Dionysiaca 26	2615 tokens, 5 seconds
[94/115] Nonnus Dionysiaca 27	2319 tokens, 4 seconds
[95/115] Nonnus Dionysiaca 28	2246 tokens, 4 seconds
[96/115] Nonnus Dionysiaca 29	2668 tokens, 5 seconds
[97/115] Nonnus Dionysiaca 30	2292 tokens, 4 seconds
[98/115] Nonnus Dionysiaca 31	2119 tokens, 4 seconds
[99/115] Nonnus Dionysiaca 32	2082 tokens, 4 seconds
[100/115] Nonnus Dionysiaca 33	2760 tokens, 5 seconds
[101/115] Nonnus Dionysiaca 34	2577 tokens, 5 seconds
[102/115] Nonnus Dionysiaca 35	2764 tokens, 5 seconds
[103/115] Nonnus Dionysiaca 36	3214 tokens, 6 seconds
[104/115] Nonnus Dionysiaca 37	5377 tokens, 10 seconds
[105/115] Nonnus Dionysiaca 38	3012 tokens, 5 seconds
[106/115] Nonnus Dionysiaca 39	2779 tokens, 5 seconds
[107/115] Nonnus Dionysiaca 40	4057 tokens, 7 seconds
[108/115] Nonnus Dionysiaca 41	2910 tokens, 5 seconds
[109/115] Nonnus Dionysiaca 42	3943 tokens, 7 seconds
[110/115] Nonnus Dionysiaca 43	2957 tokens, 5 seconds
[111/115] Nonnus Dionysiaca 44	2186 tokens, 4 seconds
[112/115] Nonnus Dionysiaca 45	2445 tokens, 4 seconds
[113/115] Nonnus Dionysiaca 46	2716 tokens, 5 seconds
[114/115] Nonnus Dionysiaca 47	5363 tokens, 10 seconds
[115/115] Nonnus Dionysiaca 48	6865 tokens, 13 seconds
total time: 0:15:44

### Create token table

In [11]:
tokens = []

for text in corpus:
    for token in text["spacy_doc"]:
        i = bisect.bisect_right(text["line_index"], token.idx) - 1
        locus = text["line_array"][i]["n"]
        if locus is None:
            continue
            
        if text["prefix"]:
            locus = text["prefix"] + "." + locus

        tokens.append(dict(
            urn = text["urn"] + ":" + locus,
            author = text["author"],
            work = text["title"],
            pref = text["prefix"],
            seq = text["line_array"][i]["seq"],
            line = text["line_array"][i]["n"],
            token = token.text,
            lemma = token.lemma_,
            pos = token.pos_,
            verbform = ";".join(token.morph.get("VerbForm")),                
            mood = ";".join(token.morph.get("Mood")),
            tense = ";".join(token.morph.get("Tense")),                
            voice = ";".join(token.morph.get("Voice")),
            person = ";".join(token.morph.get("Person")),
            number = ";".join(token.morph.get("Number")),
            case = ";".join(token.morph.get("Case")),
            gender = ";".join(token.morph.get("Gender")),
        ))

tokens = pd.DataFrame(tokens)

## Identify speech/narration

### instantiate API

In [12]:
api = DicesAPI(logfile="dices.log")

### download full speech list

In [13]:
all_speeches = api.getSpeeches()
print(len(all_speeches), "speeches")

4689 speeches

### edit two speeches

This is necessary to fix line differences between editions used by DICES and Perseus

In [14]:
for s in all_speeches:
    # missing line number in Apollonius
    if s.work.urn=="urn:cts:greekLit:tlg0001.tlg001.perseus-grc2" and s.l_la=="3.739":
        s.l_la = "3.738"

    # missing line number in Odyssey
    if s.work.urn=="urn:cts:greekLit:tlg0012.tlg002.perseus-grc2" and s.l_fi=="10.456":
        s.l_fi = "10.455"

### create a table of all line numbers in order

In [15]:
all_lines = []
for text in corpus:
    for line in text["line_array"]:
        locus = line["n"]
        if locus is None:
            continue
        if text["prefix"]:
            locus = text["prefix"] + "." + locus
        all_lines.append(dict(
            urn = text["urn"] + ":" + locus,
            speech_id = None,
            speaker = None,
            addressee = None,
            level = 0,
        ))
all_lines = pd.DataFrame(all_lines)

### mark all lines that belong to speeches

In [16]:
urns = [text["urn"] for text in corpus]

for speech in all_speeches:
    
    # skip speeches that don't appear in our corpus
    if speech.work.urn not in urns:
        continue

    # determine first and last rows in table
    i_first = all_lines.index[
        all_lines["urn"].eq(speech.work.urn + ":" + speech.l_fi)
        ][0]
    i_last = all_lines.index[
        all_lines["urn"].eq(speech.work.urn + ":" + speech.l_la)
        ][0]
    
    # set speech attributes for all rows in between
    all_lines.loc[i_first:i_last, "speech_id"] = speech._attributes["public_id"]
    all_lines.loc[i_first:i_last, "speaker"] = speech.getSpkrString()
    all_lines.loc[i_first:i_last, "addressee"] = speech.getAddrString()
    all_lines.loc[i_first:i_last, "level"] = speech.level + 1

### mark Odysseus' apologue as different from his other speech

In [17]:
apologue_speech_ids = ["3F63", "A2AB"]

all_lines.loc[all_lines["speech_id"].isin(apologue_speech_ids), "speaker"] = "Odysseus-Apologue"

### Merge line table with token table to link tokens with speeches

In [18]:
df = pd.merge(all_lines, tokens, on="urn")

## Export token table

In [19]:
output_file = os.path.join(data_dir, "tokens.tsv")
df.to_csv(output_file, index=False, sep="\t")
print(f"{len(df)} tokens exported to {output_file}")

496427 tokens exported to data/tokens.tsv

## Sanity check
### how many tokens of narrative, speech do we have?

In [20]:
pd.crosstab(df["level"], df["work"])

work   Argonautica  Dionysiaca  Iliad  Odyssey  Posthomerica  Sack of Troy
level
0            31560       92115  69319    32030         51632          3749
1            13747       55169  57432    60793         16679          1058
2                0        1086    566     9468             0             0
3                0          24      0        0             0             0

### are any lines being counted twice?

In [21]:
df.groupby(["urn"]).agg(count = ("speech_id", "nunique")).query("count>1")

Empty DataFrame
Columns: [count]
Index: []